/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // Static export keeps the deployed app aligned with the product model: briefs are
  // generated by GitHub Actions, committed as JSON, then rendered as static pages.
  output: 'export',
  experimental: {
    typedRoutes: false,
  },
};

export default nextConfig;
